import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container:{
    flex:1,
  },
  pokemonsView:{
    justifyContent:'center',
    flexDirection:'row',
    flexWrap:'wrap',
    gap:30
  },
  pokemonBlock:{
    borderWidth:2,
    borderColor:'#DB68D0',
  },
  modalPokemonInfo:{

  },
  Block1:{
    alignItems:'center',
    backgroundColor:'#fe0000',
    width:400,
    height:350,
    borderBottomColor:'black',
    borderBottomWidth:15
  },
  Circle1:{
    position:'absolute',
    alignItems:'center',
    width:80,
    height:50,
    borderTopRightRadius:110,
    borderTopLeftRadius:110,
    backgroundColor:'black',
    bottom:-15,
  },
  CircleInside:{
    alignItems:'center',
    width:50, 
    height:40,
    position:'relative',
    borderTopRightRadius:110,
    borderTopLeftRadius:110,
    backgroundColor:'white',
    bottom:-10
  },
  CircleInsideCircle:{
    width:30,
    height:30,
    position:'relative',
    borderRadius:'100%',
    borderColor:'black',
    borderWidth:5,
    bottom:-10
  },
  Block2:{
    alignItems:'center',
    backgroundColor:'#fe0000',
    width:400,
    height:380,
    borderBottomColor:'black',
    borderTopWidth:15
  },
  Circle2:{
    position:'absolute',
    top:-25,
    alignItems:'center',
    width:80,
    height:50,
    borderBottomRightRadius:110,
    borderBottomLeftRadius:110,
    backgroundColor:'black',
  },
  CircleInside2:{
      alignItems:'center',
      width:50, 
      height:40,
      borderBottomRightRadius:110,
      borderBottomLeftRadius:110,
      backgroundColor:'white',
  },
  CircleInsideCircle2:{
    width:30,
    height:30,
    borderBottomRightRadius:'100%',
    borderBottomLeftRadius:'100%',
    borderColor:'black',
    borderWidth:5,
    
  }
})